### ISSUE TITLE
Desugar fall-through of [SwitchCase]s to runtime errors.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/rasta#71]
It is a `_FallThroughError` runtime error if a `SwitchCase` falls through. This is for example tested in `tests/co19/src/Language/Statements/Switch/execution_case_t02.dart`:

```
test(value) {
  var result;

  switch(value) {
    case 1:  result = 1;
             break;
    case 2:  result = 2; /// static warning - case fall-through, see "Switch"
    case 3:  result = 3; /// static warning - case fall-through, see "Switch"
    default: result = 4;
  }
  return result;
}
main() {
  Expect.equals(1, test(1));
  Expect.throws(() {test(2);});
  Expect.throws(() {test(3);});
  Expect.equals(4, test(1));
}
```

Currently this is handled in the Kernel IR -> VM Flow graph translation. If we can assume this is desugared in the front-end, we can remove that special case in the VM implementation.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 2205263002](https://codereview.chromium.org/2205263002).
