### ISSUE TITLE
Rasta should automatically include `dart:async` and `dart:core` if async features are used

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/rasta#82]
In order to implement async/await functionality the `dart:async`  library must always be included in the resulting Kernel IR file. Alternatively `rastak` needs to accept a set of additional entry points (libraries, classes, functions) which need to be added in addition to the main library.

**Comment by peter-ahe-google** [comment]
This should be fixed by the fix for #84. If not, add an import of `dart:async` to `core_patch.dart`.
