### ISSUE TITLE
Implement redirecting factory bodies

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/rasta#87]
These seem to be unimplemented.  They are used in the core libraries (e.g., class Map).

**Comment by kmillikin** [comment]
We discussed this, and for now we'd just like to replace calls to redirecting constructors with a call to their actual target.

An example where this doesn't happen is in `NoSuchMethodError._throwNew` in the VM's core library implementation.  The call `new Map<Symbol, dynamic>` should redirect to `new LinkedHashMap<Symbol, dynamic>` which is a regular (not redirecting) factory constructor.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 2213543003](https://codereview.chromium.org/2213543003).
